### ISSUE TITLE
Symlink dists/stable to dists/buster and other dists respectively

### ISSUE THREAD

**Issue by Zocker1999NET** [mopidy/apt#2]
It's common for Debian that if you wish to be always at the stable version and do not want to change the distributions version name for every source, you just use `stable` / `oldstable` as distribution name for each apt source. However this repository does not support this.

If GitHub Pages and your workflow with this repository supports this, it would be quite handy if you symlink these dists directories accordingly to the Debian project. These links should only needed to be adapted every two years so this should be no problem.

The current symlinks should be (the first only if you begin to build for bullseye):
```
testing -> bullseye
stable -> buster
oldstable -> stretch
oldoldstable -> jessie
```

**Comment by jodal** [comment]
If the repository where only for Debian, I'd agree.

A large share of the repository's users is running Ubuntu. If they chose to use "stable" instead of "buster", which sounds more like what you'd want, they would suddenly get a new set of packages the next time Debian releases. Those packages are highly likely to not work on the latest Ubuntu release, which when Debian releases is months older.

Thus, to avoid sudden churn and breakage in your packages unless you've updated the `sources.list` file yourself, we've chosen to not include the Debian aliases for the distributions.
