### ISSUE TITLE
Repository differente version

### ISSUE THREAD

**Issue by davidbenucci** [mopidy/apt#31]
The output of `apt show mopidy` shows 2 different results

- Mopidy **3.4.2** from bullseye branch of the repository
- Mopidy **3.4.1** from bookworm branch

Why is there this difference?

**Comment by jodal** [comment]
What distro are you using? What additional APT sources do you have related to Mopidy?

I'm guessing that you might see 3.4.1-1 from Debian 12 (bookworm) proper, and in addition have the bullseye version of apt.mopidy.com enabled, which has had version 3.4.2-1 since 2023-11-01 (https://github.com/mopidy/apt/commit/10120003e9fd110944b944ad3e7dfc197685e795).

If I'm right, and you're on Debian 12, and want to get the latest Mopidy releases as Debian packages, you should replace the bullseye version of apt.mopidy.com with the bookworm version. Following the steps at https://docs.mopidy.com/latest/installation/debian/#install-from-apt-mopidy-com once more should get you there.
